language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "10"
deploy:
  provider: script
  script: yarn build && surge --project .docz/public/ --domain notes.hieunguyen.dev
  skip_cleanup: true
  on:
    branch: master
